# Generated by Django 3.0.3 on 2020-04-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='isNav',
            new_name='is_nav',
        ),
    ]
